
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.06
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: sudo npm i -g npm@latest && npm ci  
      # because we use "npm ci" to install NPM dependencies
      # we cache "~/.npm" folder
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run: npm run style
      - run: npm run lint
      - run: npm run build:prod
      - run: npm run test:coverage -- --watch=false
      - run:
          name: Tar & Gzip compiled app
          command: tar zcf dist.tar.gz dist/local-weather-app
      - store_artifacts:
          path: dist.tar.gz
workflows:
  version: 2
  build-and-test:
    jobs:
      - build